import './app.js'; import { db, chatIdFor } from './firebase.js'; import { collection, doc, getDocs, getDoc, query, serverTimestamp, setDoc, deleteDoc, where, writeBatch, onSnapshot } from 'https://www.gstatic.com/firebasejs/12.17.0/firebase-firestore.js';
        const me = window.app.current; const panel = document.querySelector('#panel'); let active = 'friends'; const cache = new Map();
        async function user(uid) { if (cache.has(uid)) return cache.get(uid); const d = await getDoc(doc(db, 'users', uid)); const u = d.data(); cache.set(uid, u); return u }
        async function connect(uid) { const batch = writeBatch(db); batch.set(doc(db, 'requests', uid, 'incoming', me.uid), { fromUid: me.uid, createdAt: serverTimestamp() }); batch.set(doc(db, 'requests', me.uid, 'outgoing', uid), { toUid: uid, createdAt: serverTimestamp() }); await batch.commit(); window.app.toast('Freundschaftsanfrage gesendet.', 'success'); render() }
        async function accept(uid) { const batch = writeBatch(db); batch.set(doc(db, 'connections', me.uid, 'items', uid), { status: 'accepted', createdAt: serverTimestamp() }); batch.set(doc(db, 'connections', uid, 'items', me.uid), { status: 'accepted', createdAt: serverTimestamp() }); batch.delete(doc(db, 'requests', me.uid, 'incoming', uid)); batch.delete(doc(db, 'requests', uid, 'outgoing', me.uid)); await batch.commit(); window.app.toast('Freundschaft angenommen.', 'success'); render() }
        async function reject(uid) { const b = writeBatch(db); b.delete(doc(db, 'requests', me.uid, 'incoming', uid)); b.delete(doc(db, 'requests', uid, 'outgoing', me.uid)); await b.commit(); window.app.toast('Anfrage abgelehnt.'); render() }
        async function cancel(uid) { const b = writeBatch(db); b.delete(doc(db, 'requests', me.uid, 'outgoing', uid)); b.delete(doc(db, 'requests', uid, 'incoming', me.uid)); await b.commit(); window.app.toast('Anfrage zurückgezogen.'); render() }
        async function remove(uid) { const b = writeBatch(db); b.delete(doc(db, 'connections', me.uid, 'items', uid)); b.delete(doc(db, 'connections', uid, 'items', me.uid)); await b.commit(); window.app.toast('Freund entfernt.'); render() }
        async function block(uid) { const b = writeBatch(db); b.set(doc(db, 'connections', me.uid, 'items', uid), { status: 'blocked', createdAt: serverTimestamp() }); b.delete(doc(db, 'connections', uid, 'items', me.uid)); b.delete(doc(db, 'requests', me.uid, 'incoming', uid)); b.delete(doc(db, 'requests', me.uid, 'outgoing', uid)); b.delete(doc(db, 'requests', uid, 'incoming', me.uid)); b.delete(doc(db, 'requests', uid, 'outgoing', me.uid)); await b.commit(); window.app.toast('Nutzer blockiert.'); render() }
        async function unblock(uid) { await deleteDoc(doc(db, 'connections', me.uid, 'items', uid)); window.app.toast('Blockierung aufgehoben.'); render() }
        function bind() { document.querySelectorAll('[data-action]').forEach(x => x.onclick = () => { const a = x.dataset.action, u = x.dataset.uid; ({ connect, accept, reject, cancel, remove, block, unblock }[a])(u) }) }
        async function list(path) { const snap = await getDocs(collection(db, ...path)); return Promise.all(snap.docs.map(async d => ({ uid: d.id, ...d.data(), user: await user(d.id) }))) }
        async function render() {
            panel.innerHTML = '<div class="loading">Lade …</div>'; let rows = []; if (active === 'friends') { rows = (await list(['connections', me.uid, 'items'])).filter(x => x.status === 'accepted'); } else if (active === 'blocked') { rows = (await list(['connections', me.uid, 'items'])).filter(x => x.status === 'blocked') } else if (active === 'incoming') { const s = await getDocs(collection(db, 'requests', me.uid, 'incoming')); rows = await Promise.all(s.docs.map(async d => ({ uid: d.id, user: await user(d.id) }))); } else { const s = await getDocs(collection(db, 'requests', me.uid, 'outgoing')); rows = await Promise.all(s.docs.map(async d => ({ uid: d.id, user: await user(d.id) }))); }
            document.querySelector('#friend-count').textContent = active === 'friends' ? rows.length : ''; panel.innerHTML = ''; if (!rows.length) { panel.innerHTML = '<div class="empty">Nichts zu sehen.</div>'; return } for (const r of rows) { const u = r.user; const button = active === 'friends' ? `<a class="secondary small" href="chat.html?uid=${r.uid}">Chat</a><button class="ghost small" data-action="remove" data-uid="${r.uid}">Entfernen</button><button class="ghost danger small" data-action="block" data-uid="${r.uid}">Blockieren</button>` : active === 'incoming' ? `<button class="primary small" data-action="accept" data-uid="${r.uid}">Annehmen</button><button class="ghost small" data-action="reject" data-uid="${r.uid}">Ablehnen</button>` : active === 'outgoing' ? `<button class="ghost small" data-action="cancel" data-uid="${r.uid}">Zurückziehen</button>` : `<button class="secondary small" data-action="unblock" data-uid="${r.uid}">Entsperren</button>`; panel.insertAdjacentHTML('beforeend', `<div class="user-row"><div class="avatar">${window.app.initials(u.username)}</div><div class="grow"><strong>${window.app.escapeHtml(u.username)}</strong><span>${window.app.escapeHtml(u.bio || 'Noch keine Bio')}</span></div><div class="row-actions">${button}</div></div>`) } bind()
        }
        document.querySelectorAll('.tabs button').forEach(b => b.onclick = () => { document.querySelectorAll('.tabs button').forEach(x => x.classList.remove('active')); b.classList.add('active'); active = b.dataset.tab; render() });
        const request = new URLSearchParams(location.search).get('request'); if (request) { try { await connect(request); history.replaceState({}, '', 'friends.html') } catch { } }
        render();
